version: 2

models:
  - name: brnz_customers
    description: "Bronze layer customer data from AdventureWorks"
    columns:
      - name: CustomerID
        description: "Primary key for customer"
        tests:
          - unique
          - not_null

      - name: FirstName
        description: "Customer first name"

      - name: LastName
        description: "Customer last name"

      - name: EmailPromotion
        description: "Email promotion preference"

      - name: StoreID
        description: "Store identifier"

      - name: TerritoryID
        description: "Sales territory"

      - name: last_modified_date
        description: "Last modified timestamp"
        tests:
          - not_null

  - name: brnz_sales_orders
    description: "Bronze layer sales order data"
    columns:
      - name: sales_order_id
        description: "Primary key"
        tests:
          - not_null

      - name: order_date
        description: "Order date"
        tests:
          - not_null
          - no_future_dates

      - name: due_date
        description: "Due date"

      - name: ship_date
        description: "Ship date"

      - name: status
        description: "Order status"

      - name: online_order_flag
        description: "Online order flag"

      - name: sales_order_number
        description: "Sales order number"

      - name: purchase_order_number
        description: "Purchase order number"

      - name: customer_id
        description: "Foreign key to customer"
        tests:
          - not_null
          - relationships:
              to: ref('brnz_customers')
              field: CustomerID

      - name: sales_person_id
        description: "Sales person ID"

      - name: territory_id
        description: "Territory ID"

      - name: order_detail_id
        description: "Order detail ID"

      - name: product_id
        description: "Product ID"

      - name: order_qty
        description: "Order quantity"

      - name: unit_price
        description: "Unit price"

      - name: unit_price_discount
        description: "Unit price discount"

      - name: line_total
        description: "Line total"
